# https://taskfile.dev

version: '3'

vars:
  GO_PACKAGES:
    sh: go list ./...
  COVERAGE_FILE: "coverage.out"

tasks:
  default:
    deps:
      - test
    
  clean:
    cmds:
      - rm -f "{{.COVERAGE_FILE}}"

  test:
    desc: runs all unit tests
    env:
      CGO_ENABLED: 1
    cmds:
      - go test -short {{catLines .GO_PACKAGES}} -race -coverprofile=coverage.out -timeout 2m
    sources:
      - "**/*.go"
    generates:
      - ./"{{.COVERAGE_FILE}}"
    silent: true

  cover:
    desc: print tests coverage
    deps:
      - test
    cmds:
      - go tool cover -func={{.COVERAGE_FILE}}
    silent: true

  lint:
    desc: runs golangci-lint linter
    cmds:
      - golangci-lint run --timeout 5m ./...
    silent: true